version: '3.9'
services:
    expressapp:
        container_name: expressapp
        build: ./server
        expose:
            - 8080
        volumes:
            - ./server:/usr/src/app
    reactapp:
        container_name: reactapp
        build: ./frontend
        expose:
            - 5000
        volumes:
            - ./frontend:/usr/src/app
    nginx:
        build: ./nginx
        ports:
            - 80:80
        links:
            - expressapp
            - reactapp
        restart: always
